work in progress on hedgehog rpi5 kernel build (cisagov/Malcolm#1098)

diff --git a/hedgehog-raspi/raspi_master.yaml b/hedgehog-raspi/raspi_master.yaml
--- a/hedgehog-raspi/raspi_master.yaml
+++ b/hedgehog-raspi/raspi_master.yaml
@@ -215,6 +215,11 @@ steps:
             "s#(^|[[:space:]])root=#\1${kernel_arg} root=#" \
             /boot/firmware/cmdline.txt
         fi
+        if ! tr ' ' '\n' < /boot/firmware/cmdline.txt |
+          grep -Fxq "$kernel_arg"; then
+          echo "Failed to add kernel argument: $kernel_arg" >&2
+          exit 1
+        fi
       done
 
       sed -i \
